micronaut:
  application:
    name: consumer-service

datasources:
  default:
    url: 'jdbc:postgres://localhost:5432/test-db'
    username: 'test'
    password: 'test'
    driverClassName: 'org.postgresql.Driver'

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations